# ansible-playbook -v -i ~/ansible/hosts /playbooks/setup-dotnet-core.yml
# ansible version of the dotnet core installation instructions from Scott Hanselman 
# https://www.hanselman.com/blog/InstallingTheNETCore2xSDKOnARaspberryPiAndBlinkingAnLEDWithSystemDeviceGpio.aspx
---
- hosts: pi-dotnet
  gather_facts: yes
  tasks:

    - name: Download .NET Core Linux ARM 32-bit SDK 
      get_url:
        url: https://download.visualstudio.microsoft.com/download/pr/9650e3a6-0399-4330-a363-1add761127f9/14d80726c16d0e3d36db2ee5c11928e4/dotnet-sdk-2.2.102-linux-arm.tar.gz
        dest: /home/pi/dotnet-sdk-2.2.102-linux-arm.tar.gz
        mode: 0440

    - name: Download dotnet core Linux ASP.NET Runtime
      get_url:
        url: https://download.visualstudio.microsoft.com/download/pr/9d049226-1f28-4d3d-a4ff-314e56b223c5/f67ab05a3d70b2bff46ff25e2b3acd2a/aspnetcore-runtime-2.2.1-linux-arm.tar.gz
        dest: /home/pi/aspnetcore-runtime-2.2.1-linux-arm.tar.gz
        mode: 0440

    - name: Create a dotnet directory if it does not exist
      file:
        path: $HOME/dotnet
        state: directory
        mode: 0755

    - name: Extract dotnet-sdk-2.2.102-linux-arm.tar.gz into /home/pi/dotnet
      become: yes
      unarchive:
        src: /home/pi/dotnet-sdk-2.2.102-linux-arm.tar.gz
        dest: /home/pi/dotnet

    - name: link to /usr/local/bin
      become: yes
      command: export DOTNET_ROOT=$HOME/dotnet && export PATH=$PATH:$HOME/dotnet

    - name: Extract aspnetcore-runtime-2.2.1-linux-arm.tar.gz into /home/pi/dotnet
      become: yes
      unarchive:
        src: /home/pi/aspnetcore-runtime-2.2.1-linux-arm.tar.gz
        dest: /home/pi/dotnet

    - name: Test the results
      become: yes
      command: dotnet --info

